# Generated by Django 3.1.7 on 2024-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_table',
            name='client_mail',
            field=models.CharField(default='a9756549615@gmail.com', max_length=300),
            preserve_default=False,
        ),
    ]
